#!/usr/bin/bash

nix_profile="$HOME/.nix-profile/etc/profile.d/nix.sh" 
export LD_LIBRARY_PATH=

echo "which nix: '$(which nix)'"
echo "which nixstatic: '$(which nix-user-chroot)'"
echo "which nix-user-chroot: '$(which nixstatic)'"
echo "ls -l '$nix_profile': '$(ls -l "$nix_profile" 2>/dev/null)'"

# we might want to replace that command with nixstatic
_nix=nix

if [ -z "$(which nix)" ]; then
	if [ -n "$(which nixstatic)" -a '!' -v NIX_STORE ]; then
		# use nixstatic to start the develop shell
		_nix=nixstatic
	elif [ -f "$nix_profile" -a '!' -v NIX_STORE ]; then
		# load the env vars for nix, if we're in a nix-user-chroot environment
		. "$nix_profile"
	elif [ -n "$(which nix-user-chroot)" -a '!' -v BNIX_RECURSION ]; then
		echo "using nix-user-chroot ~/.nix bash $0"
		# if we're not in a nix-user-chroot environment, but can start one, start that and call this script.
		# set a recursion marker to avoid infinite recursion.
		BNIX_RECURSION=1 nix-user-chroot ~/.nix bash $0;
	else
		echo "we don't know, where nix is, we don't have the nix-profile .sh " \
			"and we don't even have nix-user-chroot for a start."
	fi
fi

if [ -n "$(which $_nix)" ]; then
	# start the nix shell
	$_nix --extra-experimental-features 'nix-command flakes' develop
else
	echo "we still have no 'nix' (more precisely: command '$_nix') to execute!";
fi
